name=EposCAN
version=2.0.0
author=Mantis Research Group
maintainer=Mantis Research Group <mantis@on.uclm.es>
sentence=CANopen support for ESP-IDF.
paragraph=Arduino library for CANopen server-side and client-side communication.
category=Communication
url=https://github.com/uclm-mantis/epos
architectures=esp32
