import pandas as pd
import numpy as np
import re

df = pd.read_csv(
    'od.csv',
    delimiter=';',
    usecols=[0, 1, 2, 3, 4, 5, 6],
    names=['index', 'subindex', 'description', 'type', 'access', 'rxPDO', 'txPDO'],
    header=0,  # Usa la primera fila como encabezado
    engine='python'
)


def generate_c_identifier(description):
    description = description.replace('(', '').replace(')', '')
    # Reemplazar cualquier otro carácter no alfanumérico por _
    identifier = re.sub(r'[^a-zA-Z0-9]', '_', description)
    # Asegurar que no inicie con un número
    if identifier[0].isdigit():
        identifier = f"_{identifier}"
    return identifier.lower()

def generate_ctype(t):
    unknown = "unknown_t"
    return {
        "ARRAY": unknown,
        "INTEGER8": "int8_t",
        "INTEGER16": "int16_t",
        "INTEGER32": "int32_t",
        "INTEGER64": "int64_t",
        "RECORD": unknown,
        "STRUCT": unknown,
        "DOMAIN": unknown,
        "UNSIGNED8": "uint8_t",
        "UNSIGNED16": "uint16_t",
        "UNSIGNED32": "uint32_t",
        "UNSIGNED64": "uint64_t",
        "STRING4": "string4_t",
        "STRING8": "string8_t",
    }[t]

df['c_identifier'] = df['description'].apply(generate_c_identifier)
df['setter'] = np.where(
    df['access'].isin(['RW', 'WO']),
    'set_' + df['c_identifier'].str.lower().str.lstrip('_'),
    'NA'
)
df['getter'] = np.where(
    df['access'].isin(['RW', 'RO', 'CONST']),
    'get_' + df['c_identifier'].str.lower().str.lstrip('_'),
    'NA'
)
df['ctype'] = df['type'].apply(generate_ctype)

header_file = 'include/object_dictionary.h'


od = []
for _, r in df.iterrows():
    idx, subidx, desc, id, t, rxPDO, txPDO, setter, getter = r['index'], r['subindex'], r['description'], r['c_identifier'], r['ctype'], r['rxPDO'], r['txPDO'], r['setter'], r['getter']
    if desc.startswith('Internal '): continue
    obj = f"OBJ({idx}, {subidx}, \"{desc}\", {id}, {t}, {rxPDO}, {txPDO}, {getter}, {setter})"
    od.append(obj)

with open(header_file, 'w') as f:
    f.write(
'''// DO NOT EDIT. This file is autogenerated with 'extract.py' tool
// Format: OBJ(index, subindex, desc, identifier, type, rxPDO, txPDO, getter, setter)
'''
    )
    f.write('\n'.join(od))

print(f"Generated header file: {header_file}")

df.to_csv(
    'data/object-dictionary.csv',
    index=False,  # No incluir la columna de índices en el archivo
    sep=';',      # Usar el mismo delimitador que el archivo original
    header=True   # Incluir los nombres de las columnas como primera línea
)